### ISSUE TITLE
Modify session list columns

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/VAMDashboard#18]
* Source host:port
* Opened (connected)
* Closed
* Duration

## Tasks
* [x] Change columns
* [x] Timestamp year should be 2 digits
* [x] "Closed" only shows date if different from "Opened"
* [x] "Duration" should show seconds if < 1 minute

**Comment by mfuroyama** [comment]
Done
